name: core
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build-core:
    runs-on: ubuntu-latest
    container:
      image: docker:24.0.7
      env:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    steps:
    - name: Build core automation 
      run: |
        apk add git make

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/netbootxyz/${{ github.workflow }}:latest
          ghcr.io/netbootxyz/${{ github.workflow }}:${{ github.sha }}
