name: pull-requests

on:
  pull_request:
    branches:
      - main

jobs:
  test-pr:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
    - name: Syntax Check
      run: |
        ansible-playbook -i inventory site.yml --syntax-check
    - name: Ansible lint
      run: |
        ansible-lint -v roles/netbootxyz/tasks
